<?php
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type");
header("Content-Type: application/json; charset=UTF-8");

// Debug Logging Function
function logDebug($message)
{
    // Ensure this file is writable by the web server
    $logFile = __DIR__ . '/sync_debug.log';
    $timestamp = date('[Y-m-d H:i:s] ');
    file_put_contents($logFile, $timestamp . $message . PHP_EOL, FILE_APPEND);
}

// Handle preflight request
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit();
}

// Database Credentials
$host = "localhost:3306";
$db_name = "sevensmile_booking";
$username = "sevensmile_booking";
$password = "YY8ewaKy?ql44n&k";

try {
    $conn = new PDO("mysql:host=" . $host . ";dbname=" . $db_name . ";charset=utf8mb4", $username, $password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $exception) {
    logDebug("Connection Error: " . $exception->getMessage());
    http_response_code(500);
    echo json_encode(["status" => "error", "message" => "Connection error: " . $exception->getMessage()]);
    exit();
}

// Get JSON input
$inputJSON = file_get_contents('php://input');
logDebug("Received Input: " . $inputJSON); // Log raw input

if (!$inputJSON) {
    logDebug("Input is empty (Possibly GET request or Redirect)");
    // Don't exit with error immediately, let's see why. 
    // Actually, if input is empty for POST, it's an issue.
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        logDebug("Empty POST body received.");
        http_response_code(400);
        echo json_encode(["status" => "error", "message" => "Empty POST body"]);
        exit();
    }
}

$input = json_decode($inputJSON, true);

if (!$input && $_SERVER['REQUEST_METHOD'] === 'POST') {
    logDebug("JSON Decode Error: " . json_last_error_msg() . " | Raw Input: " . substr($inputJSON, 0, 100));
    http_response_code(400);
    echo json_encode(["status" => "error", "message" => "Invalid JSON input"]);
    exit();
}

$table = filter_var($input['table'], FILTER_SANITIZE_STRING);
$action = filter_var($input['action'], FILTER_SANITIZE_STRING); // insert, update, delete
$data = $input['data'] ?? [];
$primaryKey = $input['primaryKey'] ?? 'id';

logDebug("Action: $action, Table: $table");

if (!$table || !$action || empty($data)) {
    logDebug("Missing Fields");
    http_response_code(400);
    echo json_encode(["status" => "error", "message" => "Missing required fields (table, action, data)"]);
    exit();
}

// Allowed tables whitelist for security
$allowedTables = ['information', 'users', 'orders', 'tour_bookings', 'transfer_bookings', 'payments', 'vouchers', 'invoices'];
if (!in_array($table, $allowedTables)) {
    logDebug("Table Not Allowed: $table");
    http_response_code(403);
    echo json_encode(["status" => "error", "message" => "Table not allowed"]);
    exit();
}

try {
    if ($action === 'insert') {
        // Remove ID from insert data if it exists (let MySQL auto-increment handle it)
        // Check if the ID in data is actually a valid number (generated by Supabase maybe?)
        // If Supabase sends an ID, we might want to keep it to ensure sync? 
        // BUT MySQL usually has its own AUTO_INCREMENT. 
        // SAFE BET: If the ID is clearly large/integer, we might try to insert it, but if it conflicts, we might have issues.
        // DECISION: For 'information' table, ID is auto-increment in MySQL schema.
        // Supabase ID IS the source of truth if we want 1:1 sync. 
        // Let's TRY to insert with ID. If it exists, we perhaps should update?
        // For now, let's just Insert.

        $columns = array_keys($data);
        $placeholders = array_map(function ($col) {
            return ":" . $col;
        }, $columns);

        $sql = "INSERT INTO " . $table . " (" . implode(", ", $columns) . ") VALUES (" . implode(", ", $placeholders) . ")";

        $stmt = $conn->prepare($sql);
        foreach ($data as $key => $value) {
            if (is_bool($value)) {
                $value = $value ? 1 : 0;
            } elseif (is_array($value) || is_object($value)) {
                $value = json_encode($value);
            }
            $stmt->bindValue(":" . $key, $value);
        }
        $stmt->execute();

        $lastId = $conn->lastInsertId();
        logDebug("Insert Success. Last ID: $lastId");
        echo json_encode(["status" => "success", "message" => "Inserted successfully", "id" => $lastId]);
    } elseif ($action === 'update') {
        if (!isset($data[$primaryKey])) {
            throw new Exception("Primary key ($primaryKey) not found in data for update");
        }

        $id = $data[$primaryKey];
        unset($data[$primaryKey]); // Remove PK from update fields

        if (empty($data)) {
            echo json_encode(["status" => "success", "message" => "No fields to update"]);
            exit();
        }

        $setParts = [];
        foreach (array_keys($data) as $col) {
            $setParts[] = "$col = :$col";
        }

        $sql = "UPDATE " . $table . " SET " . implode(", ", $setParts) . " WHERE " . $primaryKey . " = :primaryKey";
        $stmt = $conn->prepare($sql);

        $stmt->bindValue(":primaryKey", $id);
        foreach ($data as $key => $value) {
            if (is_bool($value)) {
                $value = $value ? 1 : 0;
            } elseif (is_array($value) || is_object($value)) {
                $value = json_encode($value);
            }
            $stmt->bindValue(":" . $key, $value);
        }
        $stmt->execute();

        logDebug("Update Success. ID: $id");
        echo json_encode(["status" => "success", "message" => "Updated successfully"]);
    } elseif ($action === 'delete') {
        if (!isset($data[$primaryKey])) {
            throw new Exception("Primary key not found in data for delete");
        }

        $sql = "DELETE FROM " . $table . " WHERE " . $primaryKey . " = :id";
        $stmt = $conn->prepare($sql);
        $stmt->bindValue(":id", $data[$primaryKey]);
        $stmt->execute();

        logDebug("Delete Success. ID: " . $data[$primaryKey]);
        echo json_encode(["status" => "success", "message" => "Deleted successfully"]);
    } else {
        http_response_code(400);
        echo json_encode(["status" => "error", "message" => "Invalid action"]);
    }
} catch (Exception $e) {
    logDebug("Database Execute Error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(["status" => "error", "message" => "Database error: " . $e->getMessage()]);
}
